#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""This file is autogenerated by tools/generate_elementwise_ops.
Do not make manual changes.
"""

import functools

import jax
from typing import Any
from jaxonnxruntime.onnx_ops import abs
from jaxonnxruntime.onnx_ops import acos
from jaxonnxruntime.onnx_ops import acosh
from jaxonnxruntime.onnx_ops import asin
from jaxonnxruntime.onnx_ops import asinh
from jaxonnxruntime.onnx_ops import atan
from jaxonnxruntime.onnx_ops import atanh
from jaxonnxruntime.onnx_ops import ceil
from jaxonnxruntime.onnx_ops import cos
from jaxonnxruntime.onnx_ops import cosh
from jaxonnxruntime.onnx_ops import erf
from jaxonnxruntime.onnx_ops import exp
from jaxonnxruntime.onnx_ops import identity
from jaxonnxruntime.onnx_ops import leakyrelu
from jaxonnxruntime.onnx_ops import log
from jaxonnxruntime.onnx_ops import neg
from jaxonnxruntime.onnx_ops import onnx_not
from jaxonnxruntime.onnx_ops import reciprocal
from jaxonnxruntime.onnx_ops import relu
from jaxonnxruntime.onnx_ops import selu
from jaxonnxruntime.onnx_ops import sigmoid
from jaxonnxruntime.onnx_ops import sin
from jaxonnxruntime.onnx_ops import sinh
from jaxonnxruntime.onnx_ops import softplus
from jaxonnxruntime.onnx_ops import sqrt
from jaxonnxruntime.onnx_ops import tanh

from batching_security_checker.core import taint_handler
from batching_security_checker.core import taint_propagation
from batching_security_checker.onnx_ops_placeholders.autogenerated import celu
from batching_security_checker.onnx_ops_placeholders.autogenerated import elu
from batching_security_checker.onnx_ops_placeholders.autogenerated import floor
from batching_security_checker.onnx_ops_placeholders.autogenerated import hardsigmoid
from batching_security_checker.onnx_ops_placeholders.autogenerated import hardswish
from batching_security_checker.onnx_ops_placeholders.autogenerated import isinf
from batching_security_checker.onnx_ops_placeholders.autogenerated import isnan
from batching_security_checker.onnx_ops_placeholders.autogenerated import round
from batching_security_checker.onnx_ops_placeholders.autogenerated import shrink
from batching_security_checker.onnx_ops_placeholders.autogenerated import sign
from batching_security_checker.onnx_ops_placeholders.autogenerated import softsign
from batching_security_checker.onnx_ops_placeholders.autogenerated import tan
from batching_security_checker.onnx_ops_placeholders.autogenerated import thresholdedrelu


@functools.partial(jax.jit, static_argnames=())
def onnx_taint_elementwise_unary(*combined_args):
  """The internal jax impl for onnx binary elementwise ops."""
  input_args, taint_input_args = taint_handler.split_args(combined_args, op="elementwise_unary")

  assert len(input_args) == 1
  assert len(taint_input_args) == 1
  out = taint_propagation.identity_taint(taint_input_args[0])
  return out


class TaintAbs(abs.Abs, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {abs.onnx_abs: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return abs.Abs


class TaintAcos(acos.Acos, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {acos.onnx_acos: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return acos.Acos


class TaintAcosh(acosh.Acosh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {acosh.onnx_acosh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return acosh.Acosh


class TaintAsin(asin.Asin, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {asin.onnx_asin: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return asin.Asin


class TaintAsinh(asinh.Asinh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {asinh.onnx_asinh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return asinh.Asinh


class TaintAtan(atan.Atan, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {atan.onnx_atan: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return atan.Atan


class TaintAtanh(atanh.Atanh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {atanh.onnx_atanh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return atanh.Atanh


class TaintCeil(ceil.Ceil, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {ceil.onnx_ceil: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return ceil.Ceil


class TaintCelu(celu.Celu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {celu.onnx_celu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return celu.Celu


class TaintCos(cos.Cos, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {cos.onnx_cos: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return cos.Cos


class TaintCosh(cosh.Cosh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {cosh.onnx_cosh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return cosh.Cosh


class TaintElu(elu.Elu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {elu.onnx_elu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return elu.Elu


class TaintErf(erf.Erf, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {erf.onnx_erf: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return erf.Erf


class TaintExp(exp.Exp, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {exp.onnx_exp: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return exp.Exp


class TaintFloor(floor.Floor, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {floor.onnx_floor: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return floor.Floor


class TaintHardSigmoid(hardsigmoid.HardSigmoid, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {hardsigmoid.onnx_hardsigmoid: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return hardsigmoid.HardSigmoid


class TaintHardSwish(hardswish.HardSwish, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {hardswish.onnx_hardswish: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return hardswish.HardSwish


class TaintIdentity(identity.Identity, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {identity.onnx_identity: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return identity.Identity


class TaintIsInf(isinf.IsInf, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {isinf.onnx_isinf: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return isinf.IsInf


class TaintIsNaN(isnan.IsNaN, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {isnan.onnx_isnan: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return isnan.IsNaN


class TaintLeakyRelu(leakyrelu.LeakyRelu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {leakyrelu.onnx_leakyrelu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return leakyrelu.LeakyRelu


class TaintLog(log.Log, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {log.onnx_log: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return log.Log


class TaintNeg(neg.Neg, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {neg.onnx_neg: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return neg.Neg


class TaintNot(onnx_not.Not, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {onnx_not.onnx_not: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return onnx_not.Not


class TaintReciprocal(reciprocal.Reciprocal, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {reciprocal.onnx_reciprocal: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return reciprocal.Reciprocal


class TaintRelu(relu.Relu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {relu.onnx_relu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return relu.Relu


class TaintRound(round.Round, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {round.onnx_round: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return round.Round


class TaintSelu(selu.Selu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {selu.onnx_selu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return selu.Selu


class TaintShrink(shrink.Shrink, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {shrink.onnx_shrink: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return shrink.Shrink


class TaintSigmoid(sigmoid.Sigmoid, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sigmoid.onnx_sigmoid: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return sigmoid.Sigmoid


class TaintSign(sign.Sign, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sign.onnx_sign: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return sign.Sign


class TaintSin(sin.Sin, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sin.onnx_sin: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return sin.Sin


class TaintSinh(sinh.Sinh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sinh.onnx_sinh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return sinh.Sinh


class TaintSoftplus(softplus.Softplus, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {softplus.onnx_softplus: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return softplus.Softplus


class TaintSoftsign(softsign.Softsign, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {softsign.onnx_softsign: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return softsign.Softsign


class TaintSqrt(sqrt.Sqrt, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sqrt.onnx_sqrt: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return sqrt.Sqrt


class TaintTan(tan.Tan, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {tan.onnx_tan: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return tan.Tan


class TaintTanh(tanh.Tanh, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {tanh.onnx_tanh: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return tanh.Tanh


class TaintThresholdedRelu(thresholdedrelu.ThresholdedRelu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {thresholdedrelu.onnx_thresholdedrelu: onnx_taint_elementwise_unary}

  @classmethod
  def data_handler(cls):
    return thresholdedrelu.ThresholdedRelu

