#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""This file is autogenerated by tools/generate_elementwise_ops.
Do not make manual changes.
"""

import functools

import jax
from typing import Any
from jaxonnxruntime.onnx_ops import add
from jaxonnxruntime.onnx_ops import and_op
from jaxonnxruntime.onnx_ops import bitshift
from jaxonnxruntime.onnx_ops import div
from jaxonnxruntime.onnx_ops import equal
from jaxonnxruntime.onnx_ops import greater
from jaxonnxruntime.onnx_ops import greaterorequal
from jaxonnxruntime.onnx_ops import less
from jaxonnxruntime.onnx_ops import lessorequal
from jaxonnxruntime.onnx_ops import mul
from jaxonnxruntime.onnx_ops import or_op
from jaxonnxruntime.onnx_ops import prelu
from jaxonnxruntime.onnx_ops import pow
from jaxonnxruntime.onnx_ops import sub

from batching_security_checker.core import taint_handler
from batching_security_checker.core import taint_propagation
from batching_security_checker.onnx_ops_placeholders.autogenerated import mod
from batching_security_checker.onnx_ops_placeholders.autogenerated import xor


@functools.partial(jax.jit, static_argnames=())
def onnx_taint_elementwise_binary(*combined_args):
  """The internal jax impl for onnx binary elementwise ops."""
  input_args, taint_input_args = taint_handler.split_args(combined_args, op="elementwise_binary")

  assert len(input_args) == 2
  assert len(taint_input_args) == 2
  a, b = taint_input_args
  out = taint_propagation.binary_elementwise_taint(a, b)
  return out


class TaintAdd(add.Add, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {add.onnx_add: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return add.Add


class TaintAnd(and_op.And, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {and_op.onnx_and: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return and_op.And


class TaintBitShift(bitshift.BitShift, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {bitshift.onnx_bitshift: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return bitshift.BitShift


class TaintDiv(div.Div, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {div.onnx_div: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return div.Div


class TaintEqual(equal.Equal, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {equal.onnx_equal: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return equal.Equal


class TaintGreater(greater.Greater, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {greater.onnx_greater: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return greater.Greater


class TaintGreaterOrEqual(greaterorequal.GreaterOrEqual, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {greaterorequal.onnx_greaterorequal: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return greaterorequal.GreaterOrEqual


class TaintLess(less.Less, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {less.onnx_less: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return less.Less


class TaintLessOrEqual(lessorequal.LessOrEqual, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {lessorequal.onnx_lessorequal: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return lessorequal.LessOrEqual


class TaintMod(mod.Mod, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {mod.onnx_mod: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return mod.Mod


class TaintMul(mul.Mul, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {mul.onnx_mul: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return mul.Mul


class TaintOr(or_op.Or, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {or_op.onnx_or: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return or_op.Or


class TaintPRelu(prelu.PRelu, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {prelu.onnx_prelu: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return prelu.PRelu


class TaintPow(pow.Pow, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {pow.onnx_pow: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return pow.Pow


class TaintSub(sub.Sub, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {sub.onnx_sub: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return sub.Sub


class TaintXor(xor.Xor, taint_handler.TaintHandler):

  @classmethod
  def prepare_taint_attrs(cls, attrs_dict: dict[str, Any]) -> dict[str, Any]:
    return {} # clear all attributes

  @classmethod
  def jit_lookup(cls):
    return {xor.onnx_xor: onnx_taint_elementwise_binary}

  @classmethod
  def data_handler(cls):
    return xor.Xor

