# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

"""Automatically generate label propagation for (unary and binary) elementwise ONNX operators."""

from collections.abc import Sequence
import glob
import os
from typing import Any
import warnings

from absl import app
from absl import flags
from jaxonnxruntime.onnx_ops import add
import jinja2

import onnx


FLAGS = flags.FLAGS

flags.DEFINE_string("root_dir", None, "Path to the root of the code directory.")

onnx_ops_root_dir = os.path.dirname(os.path.realpath(add.__file__))

elementwise_unary_ops = [
    "Abs",
    "Acos",
    "Acosh",
    "Asin",
    "Asinh",
    "Atan",
    "Atanh",
    "Ceil",
    "Celu",
    "Cos",
    "Cosh",
    "Elu",
    "Erf",
    "Exp",
    "Floor",
    "HardSigmoid",
    "HardSwish",
    "Identity",
    "IsInf",
    "IsNaN",
    "LeakyRelu",
    "Log",
    "Neg",
    "Not",
    "Reciprocal",
    "Relu",
    "Round",
    "Selu",
    "Shrink",
    "Sigmoid",
    "Sign",
    "Sin",
    "Sinh",
    "Softplus",
    "Softsign",
    "Sqrt",
    "Tan",
    "Tanh",
    "ThresholdedRelu",
    # "BitwiseNot", # only available in onnx v20
    # "Gelu",
    # "Mish",
    # "RegexFullMatch",
]

elementwise_binary_ops = [
    "Add",
    "And",
    "BitShift",
    "Div",
    "Equal",
    "Greater",
    "GreaterOrEqual",
    "Less",
    "LessOrEqual",
    "Mod",
    "Mul",
    "Or",
    "PRelu",
    "Pow",
    "Sub",
    "Xor",
    #    "BitwiseAnd", # only available in onnx v20
    #    "BitwiseOr",
    #    "BitwiseXor",
    #    "StringConcat",
]


def main(argv: Sequence[str]) -> None:
  del argv

  root_dir = FLAGS.root_dir

  elementwise_unary_operators = _build_operators(
      operator_names=elementwise_unary_ops, op_class="elementwise_unary"
  )

  elementwise_binary_operators = _build_operators(
      operator_names=elementwise_binary_ops, op_class="elementwise_binary"
  )

  environment = jinja2.Environment(
      loader=jinja2.FileSystemLoader(
          os.path.join(root_dir, "tools", "templates/")
      )
  )

  _create_placeholder_ops(
      operators=elementwise_binary_operators + elementwise_unary_operators,
      environment=environment,
      placeholder_ops_dir=os.path.join(
          root_dir, "batching_security_checker", "onnx_ops_placeholders", "autogenerated"
      ),
  )

  _create_elementwise_ops(
      operators=elementwise_binary_operators,
      environment=environment,
      op_class="elementwise_binary",
      taint_ops_dir=os.path.join(root_dir, "batching_security_checker", "onnx_ops"),
  )

  _create_elementwise_ops(
      operators=elementwise_unary_operators,
      environment=environment,
      op_class="elementwise_unary",
      taint_ops_dir=os.path.join(root_dir, "batching_security_checker", "onnx_ops"),
  )


def _build_operators(
    operator_names: list[str], op_class: str
) -> list[dict[str, Any]]:
  """Prepares operator definitions for label propagation code generation.

  This function takes a list of operator names and an operator class, and
  constructs a list of dictionaries. Each dictionary describes the necessary
  components for generating the label propagation code for a specific operator.

  Args:
    operator_names: A list of operator names (strings).
    op_class: The class of the operators (e.g., "binary", "unary").

  Returns:
    A list of dictionaries, where each dictionary contains information needed
    for code generation for a label propagation operator.
  """

  assert op_class in ["elementwise_binary", "elementwise_unary"]

  op_schema_dict = _get_schema_dict()

  # some operators interfere with keywords and hence are named differently
  filename_map = {
      "and": "and_op",
      "if": "if_op",
      "not": "onnx_not",
      "or": "or_op",
  }

  operators = []
  for op_name in operator_names:

    if str(op_name) not in op_schema_dict:
      raise ValueError(
          f"ONNX {op_name} is not ONNX op list"
          f" {sorted(op_schema_dict.keys())}?."
      )
    schemas = op_schema_dict[str(op_name)]
    versions = [schema.since_version for schema in schemas]

    filename = f"{filename_map.get(op_name.lower(), op_name.lower())}"

    is_placeholder = not os.path.exists(
        os.path.join(onnx_ops_root_dir, f"{filename}.py")
    )

    d = {
        "name": op_name,
        "filename": filename,
        "class": op_class,
        "versions": versions,
        "is_placeholder": is_placeholder,
    }

    operators.append(d)
  return operators


def _create_placeholder_ops(
    operators: list[dict[str, Any]],
    environment: jinja2.Environment,
    placeholder_ops_dir: str,
):
  """Creates placeholder implementations for unsupported jaxonnxruntime operators.

  Label propagation operators require corresponding jaxonnxruntime
  implementations for inference.  When a full implementation isn't available, a
  placeholder can be used. These placeholders return NaN tensor(s) with the
  expected shape, allowing label propagation to proceed.
  These placeholders should be replaced with real implementations as they become
  available.

  This function uses Jinja2 templates (from `tools/templates/`) to generate the
  placeholder implementations.  The generated files are placed in the directory
  specified by `placeholder_ops_dir` and __init__ files
  are updated accordingly.

  Args:
    operators: The operators to potentially create placeholders for.
    environment: A Jinja2 environment used to render the templates.
    placeholder_ops_dir: The directory where the generated placeholder
      implementations will be written.
  """

  init_lines = []
  placeholder_template = environment.get_template("placeholder_op.py.jinja")

  files = glob.glob(os.path.join(placeholder_ops_dir, "*.py"))

  existing_placeholder = {
      os.path.splitext(os.path.basename(f))[0] for f in files
  }
  existing_placeholder.remove("__init__")

  no_placeholder_required = set()
  need_placeholder = set()
  for op in operators:
    if op["is_placeholder"]:
      content = placeholder_template.render(op=op)
      filename = os.path.join(placeholder_ops_dir, f"{op['filename']}.py")
      with open(filename, mode="w+") as f:
        f.write(content)

      init_lines.append(
          "from"
          " batching_security_checker.onnx_ops_placeholders.autogenerated"
          f" import {op['filename']}"
      )

      need_placeholder.add(op["filename"])
    else:
      no_placeholder_required.add(op["filename"])

  unnecessary_placeholders = no_placeholder_required.intersection(
      existing_placeholder
  )
  if unnecessary_placeholders:
    raise ValueError(
        "The following placeholder operators exist but are not needed. "
        "Please delete their corresponding files: "
        f"{', '.join(sorted(unnecessary_placeholders))}"
    )

  potentially_unnecessary = existing_placeholder - need_placeholder
  if potentially_unnecessary:
    warnings.warn(
        "The following existing placeholders are potentially not needed. "
        "Please check if they can be deleted: "
        f"{', '.join(sorted(potentially_unnecessary))}"
    )

  # update init file
  filename = os.path.join(placeholder_ops_dir, "__init__.py")
  with open(filename, mode="w+") as f:
    f.write("\n".join(init_lines))


def _create_elementwise_ops(
    operators: list[dict[str, Any]],
    environment,
    op_class: str,
    taint_ops_dir: str,
):
  """Generates label propagation implementations for elementwise ONNX operators.

  Many ONNX operators perform elementwise operations on tensors. While binary
  elementwise operators (e.g., Add, Mul) each have a different inference
  implementations, they share a common label propagation implementation.
  Similarly, unary elementwise operators (e.g., Tan, Sin, Not) also share a
  common (identity function) label propagation implementation.
  This function generates the boilerplate code for these elementwise operator
  label propagation implementations.

  Args:
    operators: A list of dictionaries describing the operators to generate.
    environment: A Jinja2 environment used to render the templates.
    op_class: The class of elementwise operators being generated (e.g.,
      "binary", "unary").
    taint_ops_dir: The directory where the generated label propagation
      implementations will be written.
  """

  assert op_class in ["elementwise_binary", "elementwise_unary"]

  assert all(op["class"] == op_class for op in operators)

  template = environment.get_template(f"{op_class}.py.jinja")
  content = template.render(operators=operators)
  filename = os.path.join(taint_ops_dir, f"{op_class}.py")
  with open(filename, mode="w+") as f:
    f.write(content)


def _get_schema_dict():
  res_dict = {}
  for schema in onnx.defs.get_all_schemas_with_history():
    if schema.name not in res_dict:
      res_dict[schema.name] = []
    res_dict[schema.name].append(schema)
  return res_dict


if __name__ == "__main__":
  app.run(main)
