#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""This file is autogenerated by tools/generate_elementwise_ops.
Do not make manual changes.
"""

from collections.abc import Callable, Sequence
import functools
from typing import Any

import warnings

import jax
from jax import numpy as jnp
from jaxonnxruntime.core import handler
from jaxonnxruntime.core import onnx_node
from jaxonnxruntime.onnx_ops import onnx_ops_utils

@handler.register_op("ThresholdedRelu")
class ThresholdedRelu(handler.Handler):
  """Implementation of the ONNX ThresholdedRelu operator."""

  @classmethod
  def _prepare(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any], onnx_jax_impl: Any
  ):
    # onnx_ops_utils.update_node_attrs_dict(node, onnx_jax_impl)
    # NOTE: We ignore attributes for now.
    pass 


  @classmethod
  def version_10(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any]
  ) -> Callable[..., Any]:
    """ONNX version_10 ThresholdedRelu op."""
    cls._prepare(node, inputs, onnx_thresholdedrelu)
    return onnx_thresholdedrelu

  @classmethod
  def version_22(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any]
  ) -> Callable[..., Any]:
    """ONNX version_22 ThresholdedRelu op."""
    cls._prepare(node, inputs, onnx_thresholdedrelu)
    return onnx_thresholdedrelu




@functools.partial(jax.jit, static_argnames=())
def onnx_thresholdedrelu(*input_args):
  """https://github.com/onnx/onnx/blob/v1.12.0/docs/Operators.md#ThresholdedRelu for more details."""
  warnings.warn("This is a placeholder implementation of the ThresholdedRelu operator. Please replace with a real implementation.")
  assert len(input_args) == 1
  out = jnp.full_like(input_args[0], jnp.nan)
  return out
