#
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""This file is autogenerated by tools/generate_elementwise_ops.
Do not make manual changes.
"""

from collections.abc import Callable, Sequence
import functools
from typing import Any

import warnings

import jax
from jax import numpy as jnp
from jaxonnxruntime.core import handler
from jaxonnxruntime.core import onnx_node
from jaxonnxruntime.onnx_ops import onnx_ops_utils

@handler.register_op("Xor")
class Xor(handler.Handler):
  """Implementation of the ONNX Xor operator."""

  @classmethod
  def _prepare(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any], onnx_jax_impl: Any
  ):
    # onnx_ops_utils.update_node_attrs_dict(node, onnx_jax_impl)
    # NOTE: We ignore attributes for now.
    pass 


  @classmethod
  def version_1(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any]
  ) -> Callable[..., Any]:
    """ONNX version_1 Xor op."""
    cls._prepare(node, inputs, onnx_xor)
    return onnx_xor

  @classmethod
  def version_7(
      cls, node: onnx_node.OnnxNode, inputs: Sequence[Any]
  ) -> Callable[..., Any]:
    """ONNX version_7 Xor op."""
    cls._prepare(node, inputs, onnx_xor)
    return onnx_xor




@functools.partial(jax.jit, static_argnames=())
def onnx_xor(*input_args):
  """https://github.com/onnx/onnx/blob/v1.12.0/docs/Operators.md#Xor for more details."""
  warnings.warn("This is a placeholder implementation of the Xor operator. Please replace with a real implementation.")
  assert len(input_args) == 2
  a, b = input_args
  out_shape = jnp.broadcast_shapes(jnp.shape(a), jnp.shape(b))
  out_type = jnp.promote_types(jnp.dtype(a), jnp.dtype(b))
  out = jnp.full(out_shape, jnp.nan, dtype=out_type)
  return out
